### ISSUE TITLE
Add Belo Horizonte holidays

### ISSUE THREAD

**Issue by semente** [jadler/brazilian-holidays#1]
These are the ones I append to `calendar-holidays`:
```
(holiday-fixed 8 15 "Dia da Assunção de Nossa Senhora")
(holiday-fixed 12 8 "Dia da Imaculada Conceição")
```

**Comment by jadler** [comment]
Hello semente, support for BH holidays has been added.

**Comment by semente** [comment]
Thanks

**Comment by pedrormjunior** [comment]
I think there is a problem related to those BH holidays. Trying to install the package from MELPA, the following error appears:
```
In toplevel form:
brazilian-holidays.el:216:47: Error: Symbol’s value as variable is void: brazilian-holidays-bh-holidays
```
and the installation is unsuccessful. I didn't check the code. If you know the problem, please, let me know.

**Comment by jadler** [comment]
Hi pedrormjunior.

I made a mistake when defining the brazil-holidays-bh-holidays variable, in fact the correct thing was to create variables for states.

When I fixed this issue, I wrongly call the make-obsolete function passing brazil-holidays-bh-holidays and brazil-holidays-mg-holidays instead of call make-obsolete-variable.

Now the problem is solved.
It will be available on the next melpa build cycle.
